language: node_js

node_js:
  - '6'

env:
  - JOB=test

script:
  - if [ "$JOB" = "lint" ]; then yarn run lint; fi
  - if [ "$JOB" = "test" ]; then yarn run test-ci; fi
  - if [ "$JOB" = "build" ]; then yarn run build; fi
  - if [ "$JOB" = "test-coverage" ]; then yarn run test-coverage-ci && yarn run coverage-ci; fi

cache:
  yarn: true
  directories:
    - node_modules

matrix:
  fast_finish: true
  include:
    - node_js: "stable"
      env: JOB=lint
    - node_js: "stable"
      env: JOB=build
    - node_js: "stable"
      env: JOB=test-coverage

os:
  - linux
